version: '2'
services:
    freev2ary:
        image: freev2ary:latest
        environment: 
            - TIME=3600
            - TARGET=config/config.json
            - TEMPLATE=template.json
        volumes:
            - ./config/v2ray/config:/opt/v2ary/config
services:
    v2ray:
        image: v2ray/dev
        volumes:
            - ./config/v2ray/config:/etc/v2ray/
        ports:
            - 1085:1085
            - 1086:1086